config/routes.rb
Erdekes::Application.routes.draw do
  devise_for :students
  devise_scope :student do
    providers = Regexp.union(OmniAuth::Builder.providers.map(&:to_s))

    match "/auth/:provider", to: "omniauth_callbacks#passthru",
                             constraints: { provider: providers },
                             as: :omniauth_authorize,
                             via: [:get, :post]

    match "/auth/:provider/callback", to: "omniauth_callbacks#callback",
                                      constraints: { provider: providers },
                                      as: :omniauth_callback,
                                      via: [:get, :post]
  end
  devise_for :teachers

  namespace :admin do
    resources :courses
    resources :sections,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :lessons,   only: [:new, :edit, :create, :update, :destroy]
    resources :missions,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :solutions, only: [:new, :edit, :create, :update, :destroy] do
      get :result, on: :member
    end

    root 'courses#index'
  end

  resources :lessons, only: [:show]
  resources :missions, only: [:show]
  resources :profiles, only: [:edit, :update]
  resources :solutions, only: [:new, :create, :edit, :update]

  get 'console', to: 'home#console'
  get 'enaplostatus', to: 'home#enaplo'

  root to: 'home#index'
end

app/views/menu/_dropdown_item.html.haml
- flag ||= nil
- icon ||= nil
- url ||= nil

%li.dropdown
  %a{ :href => '#', :class => 'dropdown-toggle', :data => { :toggle => 'dropdown' }, :style => 'padding-top:5px;padding-bottom:5px' }
    - if flag
      %span{ :class => "flag-icon flag-icon-#{flag}"}
    - elsif !icon.nil?
      %span{ :class => "glyphicon glyphicon-#{icon}"}
    - elsif !url.nil?
      = image_tag url, class: 'img-circle', style: 'width:40px;height:40px'
    = name
    %b.caret
  %ul.dropdown-menu
    = yield

app/views/menu/_menu.html.haml
%nav.navbar.navbar-fixed-top.navbar-gray
  .container

    .navbar-header
      %button.navbar-toggle{ data: { toggle: 'collapse', target: '#navbar' } }
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        érdekes

    #navbar.collapse.navbar-collapse
      = render 'menu/menu_items'

app/views/menu/_menu_item.html.haml
- controllers ||= []
- actions ||= nil
- flag ||= nil
- icon ||= nil
- url ||= nil

- if actions == nil
  %li{ :class => ('active' if controllers.include?(params[:controller])) }
    = link_to "#{link}", :method => method ||= nil do
      - if flag
        %span{ :class => "flag-icon flag-icon-#{flag}"}
      - elsif !icon.nil?
        %span{ :class => "glyphicon glyphicon-#{icon}"}
      - elsif !url.nil?
        = image_tag url, class: 'media-object'
      = name
- else
  %li{ :class => ('active' if (controllers.include?(params[:controller]) && actions.include?(params[:action]))) }
    = link_to "#{link}", :method => method ||= nil do
      - if flag
        %span{ :class => "flag-icon flag-icon-#{flag}"}
      - elsif !icon.nil?
        %span{ :class => "glyphicon glyphicon-#{icon}"}
      - elsif !url.nil?
        = image_tag url, class: 'media-object'
      = name

app/views/menu/_menu_items.html.haml
%ul.nav.navbar-nav.nav-main
  = render 'menu/menu_item', link: root_path, icon: 'home', name: 'Főoldal', controllers: ['main']
  /= render 'menu/menu_item', link: events_path, icon: 'calendar', name: 'Események', controllers: ['events']
  /= render 'menu/menu_item', link: root_path, icon: 'th-large', name: 'Képek', controllers: ['gallery']
  /= render 'menu/menu_item', link: play_lists_path, icon: 'play-circle', name: 'Zenék', controllers: ['music_list']
  /= render 'menu/menu_item', link: users_path, icon: 'user', name: 'Felhasználók', controllers: ['users']

/ site switcher
%ul.nav.navbar-nav.navbar-right
  - if student_signed_in?
    = render 'menu/user_dropdown', user: current_student
  - elsif teacher_signed_in?
    = render 'menu/user_dropdown', user: current_teacher
  - else
    - OmniAuth::Builder.providers.each do |provider|
      = link_to "Belépés diákként", omniauth_authorize_path(provider), class: "btn btn-primary btn-#{provider.to_s}"

app/views/menu/_user_dropdown.html.haml
= render layout: 'menu/dropdown_item', locals: { name: user.name, url: user.profile.image ? user.profile.image : image_path('jondoe-small.png') } do
  = render 'menu/menu_item', link: edit_profile_path(user.profile), icon: 'pencil', name: 'Profilom', controllers: ['profile']
  - if user.is_a? Teacher
    = render 'menu/menu_item', link: admin_root_path, icon: 'wrench', name: 'Tanári', controllers: ['profile']
  = render 'menu/menu_item', link: send("destroy_#{user.class.name.underscore}_session_path"), method: :delete, icon: 'log-out', name: 'Kilépés'