config/routes.rb
Erdekes::Application.routes.draw do
  devise_for :students
  devise_scope :student do
    providers = Regexp.union(OmniAuth::Builder.providers.map(&:to_s))

    match "/auth/:provider", to: "omniauth_callbacks#passthru",
                             constraints: { provider: providers },
                             as: :omniauth_authorize,
                             via: [:get, :post]

    match "/auth/:provider/callback", to: "omniauth_callbacks#callback",
                                      constraints: { provider: providers },
                                      as: :omniauth_callback,
                                      via: [:get, :post]
  end
  devise_for :teachers

  namespace :admin do
    resources :courses
    resources :sections,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :lessons,   only: [:new, :edit, :create, :update, :destroy]
    resources :missions,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :solutions, only: [:new, :edit, :create, :update, :destroy] do
      get :result, on: :member
    end

    root 'courses#index'
  end

  resources :lessons, only: [:show]
  resources :missions, only: [:show]
  resources :profiles, only: [:edit, :update]
  resources :solutions, only: [:new, :create, :edit, :update]

  get 'console', to: 'home#console'
  get 'enaplostatus', to: 'home#enaplo'

  root to: 'home#index'
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :section
  has_many :solutions

  dragonfly_accessor :objectives

  scope :published, -> { where(visibility: 'public').order('updated_at DESC') }

  scope :before_deadline, -> { where('deadline > ?', Time.now).where('deadline < ?', 2.weeks.from_now) }
  scope :near_deadline,   -> { where('deadline < ?', 1.week.from_now) }

  def published
    visibility == 'public'
  end

  def example_solution
    solutions.where(student_id: nil).first
  end

  def solution_for(student)
    solutions.where(student_id: student.id).first
  end

  def doable?
    deadline.nil? || deadline > Time.now
  end

  def near_deadline?
    deadline < 1.week.from_now
  end

  def new_solutions
    solutions.without_result.without_examples.count
  end
end

app/controllers/admin/missions_controller.rb
module Admin
  class MissionsController < AdminController

    def show
      @mission = Mission.find(params[:id])

      add_breadcrumbs
    end

    def new
      @mission = Mission.new
      @section = Section.find(params[:section_id])
    end

    def create
      @mission = Mission.new(mission_params)

      if @mission.save
        redirect_to admin_section_path(@mission.section), notice: 'Mission created!'
      else
        render 'new'
      end
    end

    def edit
      @mission = Mission.find(params[:id])
      @section = @mission.section
    end

    def update
      @mission = Mission.find(params[:id])

      if @mission.update_attributes(mission_params)
        redirect_to admin_section_path(@mission.section), notice: 'Mission successfully updated!'
      else
        render 'edit'
      end
    end

    def destroy
      @mission = Mission.find(params[:id])
      @mission.destroy

      redirect_to admin_section_path(@mission.section), notice: 'Mission successfully destroyed!'
    end

    private

    def mission_params
      params.required(:mission).permit(:name, :objectives, :description, :section_id, :visibility, :deadline)
    end

    def add_breadcrumbs
      add_breadcrumb :root, admin_courses_path
      add_breadcrumb @mission.section.course.name, admin_course_path(@mission.section.course)
      add_breadcrumb @mission.section.name, admin_section_path(@mission.section)
      add_breadcrumb @mission.name
    end
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def show
    @mission = Mission.find(params[:id])
    @solution = @mission.solution_for(current_student) if student_signed_in?
  end
end

app/views/admin/missions/_form.html.haml
= semantic_form_for [:admin, @mission] do |f|
  = f.inputs name: "#{controller.action_name.capitalize} Lesson" do
    = f.input :section_id, as: :hidden, input_html: { value: @section.id }
    = f.input :name
    = f.input :deadline, as: :datetime_select
    = f.input :description, input_html: { class: 'tinymce' }
    = f.input :objectives, as: :file
    = f.input :visibility, as: :select, collection: ['private', 'public']
  = f.actions do
    = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }
    = f.action :cancel, as: :link
= tinymce

app/views/admin/missions/_result.html.haml
- for i in 0..5
  = link_to "#{i}", result_admin_solution_path(solution, result: i), remote: true, class: 'btn ' + (solution.result == i ? 'btn-default' : 'btn-primary')

app/views/admin/missions/edit.html.haml
= render 'form'

app/views/admin/missions/new.html.haml
= render 'form'

app/views/admin/missions/show.html.haml
%h1= @mission.name

%h2 Feltöltött megoldások
.section
  %ul
    - @mission.solutions.without_examples.each do |solution|
      %li.mission{ id: "solution-#{solution.id}" }
        .row
          .col-md-9
            - if solution.source_stored?
              = link_to "#{solution.student.full_name} (#{solution.student.name})", solution.source.url
            - else
              = "#{solution.student.full_name} (#{solution.student.name})"
            %p= timeago_tag solution.updated_at
          .col-md-3
            .pull-right{ id: "solution-result-#{solution.id}" }
              = render 'result', solution: solution


%p= @mission.description.html_safe
- unless @mission.example_solution
  = link_to new_admin_solution_path(mission_id: @mission), class: 'btn btn-lg btn-block btn-primary' do
    %span.glyphicon.glyphicon-plus-sign
    Upload example solution
- else
  = link_to edit_admin_solution_path(@mission.example_solution), class: 'btn btn-lg btn-block btn-warning' do
    %span.glyphicon.glyphicon-plus-edit
    Edit example solution