config/routes.rb
Erdekes::Application.routes.draw do
  devise_for :students
  devise_scope :student do
    providers = Regexp.union(OmniAuth::Builder.providers.map(&:to_s))

    match "/auth/:provider", to: "omniauth_callbacks#passthru",
                             constraints: { provider: providers },
                             as: :omniauth_authorize,
                             via: [:get, :post]

    match "/auth/:provider/callback", to: "omniauth_callbacks#callback",
                                      constraints: { provider: providers },
                                      as: :omniauth_callback,
                                      via: [:get, :post]
  end
  devise_for :teachers

  namespace :admin do
    resources :courses
    resources :sections,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :lessons,   only: [:new, :edit, :create, :update, :destroy]
    resources :missions,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :solutions, only: [:new, :edit, :create, :update, :destroy] do
      get :result, on: :member
    end

    root 'courses#index'
  end

  resources :lessons, only: [:show]
  resources :missions, only: [:show]
  resources :profiles, only: [:edit, :update]
  resources :solutions, only: [:new, :create, :edit, :update]

  get 'console', to: 'home#console'
  get 'enaplostatus', to: 'home#enaplo'

  root to: 'home#index'
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons
  has_many :missions

  scope :published, -> { where(visibility: 'public').order('updated_at DESC') }

  def published
    visibility == 'public'
  end

  def new_solutions
    missions.includes(:solutions).merge(Solution.without_result.without_examples).count
  end
end

app/controllers/admin/sections_controller.rb
module Admin
  class SectionsController < AdminController

    def show
      @section = Section.find(params[:id])
      add_breadcrumbs
    end

    def new
      @section = Section.new
      @course = Course.find(params[:course_id])
    end

    def create
      @section = Section.new(section_params)

      if @section.save
        redirect_to admin_course_path(@section.course), notice: 'Section created!'
      else
        render 'new'
      end
    end

    def edit
      @section = Section.find(params[:id])
      @course = @section.course
    end

    def update
      @section = Section.find(params[:id])

      if @section.update_attributes(section_params)
        redirect_to admin_course_path(@section.course), notice: 'Section successfully updated!'
      else
        render 'edit'
      end
    end

    def destroy
      @section = Section.find(params[:id])
      @section.destroy

      redirect_to admin_course_path(@section.course), notice: 'Section successfully destroyed!'
    end

    private

    def section_params
      params.required(:section).permit(:name, :course_id, :visibility)
    end

    def add_breadcrumbs
      add_breadcrumb :root, admin_courses_path
      add_breadcrumb @section.course.name, admin_course_path(@section.course)
      add_breadcrumb @section.name
    end
  end
end

app/views/admin/sections/_form.html.haml
= semantic_form_for [:admin, @section] do |f|
  = f.inputs name: "#{controller.action_name.capitalize} Section" do
    = f.input :course_id, as: :hidden, input_html: { value: @course.id }
    = f.input :name
    = f.input :visibility, as: :select, collection: ['private', 'public']
  = f.actions do
    = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }
    = f.action :cancel, as: :link

app/views/admin/sections/_section.html.haml
%tr
  %td
    = link_to section.name, admin_section_path(section)
    - if section.new_solutions > 0
      %span.badge.badge-danger= section.new_solutions
  %td
    .pull-right
      = link_to edit_admin_section_path(section), class: 'btn btn-warning', title: 'Edit' do
        %span.glyphicon.glyphicon-edit
      = link_to admin_section_path(section), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger', title: 'Delete' do
        %span.glyphicon.glyphicon-trash

app/views/admin/sections/edit.html.haml
= render 'form'

app/views/admin/sections/new.html.haml
= render 'form'

app/views/admin/sections/show.html.haml
%h1= "#{@section.course.name} - #{@section.name}"
.row
  .col-md-6
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Lessons
          %th
            .pull-right
      %tbody
        - @section.lessons.each do |lesson|
          %tr
            %td
              = link_to lesson.name, lesson_path(lesson)
            %td
              .pull-right
                = link_to edit_admin_lesson_path(lesson), class: 'btn btn-warning', title: 'Edit' do
                  %span.glyphicon.glyphicon-edit
                = link_to admin_lesson_path(lesson), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger', title: 'Delete' do
                  %span.glyphicon.glyphicon-trash

    =# will_paginate @courses, renderer: BootstrapPagination::Rails
    = link_to new_admin_lesson_path(section_id: @section), class: 'btn btn-lg btn-block btn-primary' do
      %span.glyphicon.glyphicon-plus-sign
      New Lesson
  .col-md-6
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Missions
          %th
            .pull-right
      %tbody
        - @section.missions.each do |mission|
          %tr
            %td
              = link_to admin_mission_path(mission) do
                = mission.name
                - if mission.new_solutions > 0
                  %span.badge.badge-danger= mission.new_solutions
            %td
              .pull-right
                = link_to edit_admin_mission_path(mission), class: 'btn btn-warning', title: 'Edit' do
                  %span.glyphicon.glyphicon-edit
                = link_to admin_mission_path(mission), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger', title: 'Delete' do
                  %span.glyphicon.glyphicon-trash

    =# will_paginate @courses, renderer: BootstrapPagination::Rails
    = link_to new_admin_mission_path(section_id: @section), class: 'btn btn-lg btn-block btn-primary' do
      %span.glyphicon.glyphicon-plus-sign
      New Mission