config/routes.rb
Erdekes::Application.routes.draw do
  devise_for :students
  devise_scope :student do
    providers = Regexp.union(OmniAuth::Builder.providers.map(&:to_s))

    match "/auth/:provider", to: "omniauth_callbacks#passthru",
                             constraints: { provider: providers },
                             as: :omniauth_authorize,
                             via: [:get, :post]

    match "/auth/:provider/callback", to: "omniauth_callbacks#callback",
                                      constraints: { provider: providers },
                                      as: :omniauth_callback,
                                      via: [:get, :post]
  end
  devise_for :teachers

  namespace :admin do
    resources :courses
    resources :sections,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :lessons,   only: [:new, :edit, :create, :update, :destroy]
    resources :missions,  only: [:show, :new, :edit, :create, :update, :destroy]
    resources :solutions, only: [:new, :edit, :create, :update, :destroy] do
      get :result, on: :member
    end

    root 'courses#index'
  end

  resources :lessons, only: [:show]
  resources :missions, only: [:show]
  resources :profiles, only: [:edit, :update]
  resources :solutions, only: [:new, :create, :edit, :update]

  get 'console', to: 'home#console'
  get 'enaplostatus', to: 'home#enaplo'

  root to: 'home#index'
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :section
  has_many :solutions

  dragonfly_accessor :objectives

  scope :published, -> { where(visibility: 'public').order('updated_at DESC') }

  scope :before_deadline, -> { where('deadline > ?', Time.now).where('deadline < ?', 2.weeks.from_now) }
  scope :near_deadline,   -> { where('deadline < ?', 1.week.from_now) }

  def published
    visibility == 'public'
  end

  def example_solution
    solutions.where(student_id: nil).first
  end

  def solution_for(student)
    solutions.where(student_id: student.id).first
  end

  def doable?
    deadline.nil? || deadline > Time.now
  end

  def near_deadline?
    deadline < 1.week.from_now
  end

  def new_solutions
    solutions.without_result.without_examples.count
  end
end

app/controllers/admin/missions_controller.rb
module Admin
  class MissionsController < AdminController

    def show
      @mission = Mission.find(params[:id])

      add_breadcrumbs
    end

    def new
      @mission = Mission.new
      @section = Section.find(params[:section_id])
    end

    def create
      @mission = Mission.new(mission_params)

      if @mission.save
        redirect_to admin_section_path(@mission.section), notice: 'Mission created!'
      else
        render 'new'
      end
    end

    def edit
      @mission = Mission.find(params[:id])
      @section = @mission.section
    end

    def update
      @mission = Mission.find(params[:id])

      if @mission.update_attributes(mission_params)
        redirect_to admin_section_path(@mission.section), notice: 'Mission successfully updated!'
      else
        render 'edit'
      end
    end

    def destroy
      @mission = Mission.find(params[:id])
      @mission.destroy

      redirect_to admin_section_path(@mission.section), notice: 'Mission successfully destroyed!'
    end

    private

    def mission_params
      params.required(:mission).permit(:name, :objectives, :description, :section_id, :visibility, :deadline)
    end

    def add_breadcrumbs
      add_breadcrumb :root, admin_courses_path
      add_breadcrumb @mission.section.course.name, admin_course_path(@mission.section.course)
      add_breadcrumb @mission.section.name, admin_section_path(@mission.section)
      add_breadcrumb @mission.name
    end
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def show
    @mission = Mission.find(params[:id])
    @solution = @mission.solution_for(current_student) if student_signed_in?
  end
end

app/views/missions/_alert.html.haml
- type = mission.near_deadline? ? 'danger' : 'warning'
- size = @missions_bd.size > 2 ? 4 : 12/@missions_bd.size
- if mission.solution_for(current_student).nil?
  %div{ class: "col-md-#{size}" }
    .alert.alert-dismissable{ class: "alert-#{type}" }
      %button.close{ 'data-dismiss' => 'alert', 'aria-hidden'=> 'true' }
        x
      %h4= "#{mission.name} - #{mission.section.course.name}"
      %p
        Ennek a feladatnak a határideje
        %span= timeago_tag mission.deadline
        %span{ style: mission.near_deadline? ? 'font-weight: bold;' : '' }= FIGYULIM[type].sample
      %p
        = link_to 'Megnézem és Feltöltöm', mission_path(mission), class: "btn btn-#{type}"

app/views/missions/_mission.html.haml
%li.mission
  .row
    .col-md-8
      = link_to mission.name, mission_path(mission)
      %p= timeago_tag mission.created_at
      - if mission.doable?
        %p.deadline
          Határidő:
          = timeago_tag mission.deadline
    .col-md-4
      .pull-right
        - if student_signed_in? && mission.doable?
          - if mission.solution_for(current_student)
            = link_to edit_solution_path(mission.solution_for(current_student)), class: 'btn btn-info tooltipable', id: "solution_for_#{mission.id}" do
              %span.glyphicon.glyphicon-edit
          - else
            = link_to new_solution_path(mission: mission), class: 'btn btn-success tooltipable', id: "solution_for_#{mission.id}" do
              %span.glyphicon.glyphicon-open
          .htp{id: "solution_for_#{mission.id}-tooltip"}
            Megoldás feltöltése
            = mission.name
            feladatra
        - if mission.example_solution.try(:published)
          = link_to 'Megoldás', mission.example_solution.source.url, class: 'btn btn-warning'

app/views/missions/show.html.haml
%h2= @mission.name
.section
  %ul
    - if @mission.objectives_stored?
      %li.mission
        .row
          .col-md-9
            = link_to 'Letölthető állomány', @mission.objectives.url
            %p= timeago_tag @mission.created_at
    - if student_signed_in? && @mission.doable?
      %li{ class: @solution.nil? ? 'mission' : 'lesson' }
        .row
          .col-md-9
            - if @solution
              %p.title Új megoldás feltöltése a feladatra
              %p
                Előző feltöltve ekkor:
                = timeago_tag @solution.updated_at
            - else
              %p.title Megoldás feltöltése a feladatra
          .col-md-3
            .pull-right
              - if @mission.doable?
                - if @solution
                  = link_to edit_solution_path(@solution), class: 'btn btn-info tooltipable', id: "solution_for_#{@mission.id}" do
                    %span.glyphicon.glyphicon-edit
                - else
                  = link_to new_solution_path(mission: @mission), class: 'btn btn-success tooltipable', id: "solution_for_#{@mission.id}" do
                    %span.glyphicon.glyphicon-open
                .htp{id: "solution_for_#{@mission.id}-tooltip"}
                  Megoldás feltöltése
                  = @mission.name
                  feladatra
%p= @mission.description.try(:html_safe)